name: Test Workflow

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: |
          echo "Workflow is running!"
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
